# 评论模板配置

# 积极评论
positive_comments:
  - "{product}的品质非常满意，正山堂不愧是高端红茶代表"
  - "{product}香气馥郁，回甘持久，非常符合我的口味"
  - "包装很精致，送礼很有面子，收到的朋友赞不绝口"
  - "店员对产品知识讲解专业，服务态度很好"
  - "正山堂的茶叶确实与众不同，值得这个价格"
  - "{product}口感醇厚细腻，茶香在口腔中久久不散"
  - "这里的环境很雅致，品茶氛围营造得很到位"
  - "店内的茶艺表演很精彩，增强了对{product}的理解"
  - "茶道老师讲解很细致，学到了正确冲泡{product}的方法"
  - "店内香气扑鼻，环境安静舒适，很适合静心品茶"
  - "店员推荐的{product}很符合我的口味，专业度很高"
  - "茶叶来源可追溯，让人喝得放心，尤其是{product}"
  - "VIP会员室环境很好，服务更加贴心，值得成为会员"
  - "积分兑换的礼品很实用，增加了购物乐趣"
  - "会员日活动很给力，{product}的折扣很实惠"

# 中性评论
neutral_comments:
  - "{product}品质不错，但价格略高，希望能有更多优惠"
  - "茶叶品质符合预期，但包装可以再精致些"
  - "服务热情，但希望能提供更多品鉴体验"
  - "口感不错，但与宣传的略有差距"
  - "环境不错但客流量有点大，休息区显得拥挤"
  - "茶艺表演很好，但场次太少，希望能增加"
  - "{product}口感还可以，但保存方法介绍不够详细"
  - "会员积分有点难攒，希望能多些积分加速活动"
  - "定制服务不错，但周期有点长，希望能加快些"
  - "有机认证区的产品选择不够多，希望能丰富些"
  - "店员态度好但有些知识点解答不够专业"
  - "试饮区的杯具不够精致，与店铺档次有些不符"
  - "产品价格比网上贵一些，希望能有线下专属优惠"

# 浏览评论
browsing_comments:
  - "价格超出预算，决定再考虑考虑"
  - "今天主要是来了解正山堂的产品系列，下次再购买"
  - "对金骏眉很感兴趣，但需要先了解更多"
  - "希望能有更多的促销活动，价格更亲民些"
  - "来了解红茶文化和历史，收获不少"
  - "想先买小包装试试味道，可惜没有小规格的"
  - "店里人太多了，打算改天再来仔细选购"
  - "在比较几家茶叶店后再做决定，先收集信息"
  - "朋友推荐来的，产品确实不错，但需要和家人商量"
  - "对定制茶礼服务很感兴趣，需要回去确认送礼名单"
  - "茶艺表演很吸引人，下次一定要参加"
  - "喜欢这里的氛围，打算下次带朋友一起来"
  - "等发工资了再来买，先记下几款感兴趣的茶"
  - "会员制度挺好的，考虑要不要办会员卡"
  - "听店员介绍了很多知识，需要消化一下再决定买什么"

# 环境评论
environment_comments:
  - "店面设计很有中国传统韵味，很符合正山堂的品牌调性"
  - "试茶区的座椅很舒适，可以慢慢品茶不受打扰"
  - "背景音乐选得很棒，茶香配乐，别有一番意境"
  - "灯光设计很巧妙，既不刺眼又能看清茶色茶形"
  - "店内古色古香的装饰很有文化底蕴，拍照很上镜"
  - "文化展示区的历史资料很丰富，增加了对红茶的了解"
  - "试茶区水温控制得很专业，冲泡出来的茶汤颜色很漂亮"

# 服务评论
service_comments:
  - "店员不会强制推销，而是根据我的口味做推荐，很舒服"
  - "茶艺师的手法很专业，每个动作都赏心悦目"
  - "店员记得我上次买的茶叶，这次还特意问我口感如何"
  - "讲解很耐心，即使问很多问题也不厌其烦"
  - "包装服务很细致，礼品包装做得特别精美"
  - "会员生日有专属优惠和礼物，很有心意"
  - "提供免费停车券，解决了我最担心的问题"

# 促销评论
promotion_comments:
  - "季节限定款很吸引人，每季都想来看看新品"
  - "会员专享品鉴会很高端，值得专程参加"
  - "积分换购的礼品种类丰富，很实用"
  - "节日促销力度大，买到就是赚到"
  - "新品上市有试饮活动，能充分了解口感"
  - "买满额赠送的茶具很精美，设计独特"
  - "老客户回购有额外赠品，感觉很受重视"

# 负面评论
negative_comments:
  - "{product}口感一般，达不到这个价位应有的水平"
  - "包装精美但内容与描述有差距，有点失望"
  - "价格偏高但体验一般，性价比不高"
  - "保存不当导致茶叶受潮，口感大打折扣"
  - "店内太吵，无法静心品茶"
  - "试喝茶壶清洗不彻底，多种茶味混杂"
  - "等候时间过长，服务不够高效"

# 年轻消费者评论
young_consumer_comments:
  - "能用积分换的文创周边太可爱了，会一直回购攒积分"
  - "产品包装很适合拍照发社交媒体，朋友都很羡慕"
  - "茶饮体验区的创意茶饮结合传统与现代，很新颖"
  - "品牌故事很有共鸣，喜欢这种传承与创新的精神"
  - "微信小程序的会员体系很便捷，积分自动计算很方便"
  - "定制的个性化标签和包装很特别，送礼倍有面子"
  - "线上预约品鉴会很方便，不用排队等候" 