# API配置
api:
  key: "f0b94d12aa98c64426df53f87551a702fd2032c6"
  base_url: "https://aistudio.baidu.com/llm/lmapi/v3"
  model_name: "ernie-4.0-turbo-128k"
  timeout: 90
  connect_timeout: 15  # 连接超时时间，单位秒
  read_timeout: 90     # 读取超时时间，单位秒
  write_timeout: 30    # 写入超时时间，单位秒
  interval: 5          # 请求间隔时间，单位秒，避免访问过于频繁
  max_retries: 5       # 最大重试次数
  retry_interval: 8    # 初始重试间隔时间，单位秒
  max_retry_interval: 60  # 最大重试间隔时间，单位秒
  retry_codes: [408, 429, 500, 502, 503, 504]  # 需要重试的HTTP状态码
  cache_enabled: true  # 启用缓存
  cache_time: 3600     # 缓存有效期，单位秒

# 场所配置
locations:
  - 茶艺体验区
  - 产品展示区 
  - 文化传承区
  - 个人定制区
  - 礼品专区
  - 有机认证区
  - 品牌故事区
  - 会员服务区

# 表情符号列表
emojis:
  - 👍✨
  - 😊🍵
  - 🤔💭
  - 😄🫖
  - 🧐📊
  - 🌿👌
  - ❤️🍃
  - 💯🏆

# 消费者地域分布
consumer_regions:
  华东: ["上海", "江苏", "浙江", "安徽", "福建", "江西", "山东"]
  华南: ["广东", "广西", "海南"]
  华中: ["湖北", "湖南", "河南"]
  华北: ["北京", "天津", "河北", "山西", "内蒙古"]
  西南: ["重庆", "四川", "贵州", "云南", "西藏"]
  西北: ["陕西", "甘肃", "青海", "宁夏", "新疆"]
  东北: ["辽宁", "吉林", "黑龙江"]

# 消费者地域类型
consumer_region_types:
  一线城市: ["北京", "上海", "广州", "深圳"]
  新一线城市: ["成都", "杭州", "武汉", "西安", "南京", "天津", "苏州", "郑州", "长沙", "东莞", "宁波", "佛山", "合肥", "青岛"]
  二线城市: ["沈阳", "厦门", "福州", "济南", "大连", "贵阳", "昆明", "南宁", "南昌", "太原", "石家庄", "哈尔滨", "长春", "常州", "徐州", "无锡", "嘉兴", "温州"]
  三四线城市: []  # 除了上述城市外的其他城市
  县城: []
  农村: []

# 消费者地域分布
consumer_region_distribution:
  传统茶文化爱好者:
    一线城市: 0.25
    新一线城市: 0.35
    二线城市: 0.25
    三四线城市: 0.10
    县城: 0.05
    农村: 0.00
  品质生活追求者:
    一线城市: 0.35
    新一线城市: 0.40
    二线城市: 0.20
    三四线城市: 0.05
    县城: 0.00
    农村: 0.00
  商务人士:
    一线城市: 0.40
    新一线城市: 0.35
    二线城市: 0.20
    三四线城市: 0.05
    县城: 0.00
    农村: 0.00
  健康生活主义者:
    一线城市: 0.30
    新一线城市: 0.35
    二线城市: 0.25
    三四线城市: 0.10
    县城: 0.00
    农村: 0.00
  年轻新贵:
    一线城市: 0.45
    新一线城市: 0.35
    二线城市: 0.15
    三四线城市: 0.05
    县城: 0.00
    农村: 0.00

# 消费者年龄范围
age_ranges:
  传统茶文化爱好者: [40, 65]
  品质生活追求者: [30, 45]
  商务人士: [35, 55]
  健康生活主义者: [28, 50]
  年轻新贵: [18, 35]

# 模拟参数优化
simulation:
  batch_size: 3        # 每批模拟的消费者数量
  batch_count: 3       # 分批数量
  simplified_prompt: true  # 使用简化提示词 