# 消费心理特征配置

传统茶文化爱好者:
  价格敏感度: 低  # 低:对价格不敏感，高:对价格敏感
  品牌忠诚度: 高  # 高:品牌忠诚度高，低:品牌忠诚度低
  品质要求: 极高  # 极高/高/中/低
  决策速度: 慢  # 快/中/慢
  购买动机: 文化传承、品质享受
  信息获取渠道:
    - 茶文化活动
    - 专业杂志
    - 实体店铺
  购买影响因素:
    - 产品品质
    - 历史传承
    - 制作工艺
  复购概率: 0.85

品质生活追求者:
  价格敏感度: 中
  品牌忠诚度: 中高
  品质要求: 高
  决策速度: 中
  购买动机: 品质生活、社交展示
  信息获取渠道:
    - 社交媒体
    - 朋友推荐
    - 品牌官网
  购买影响因素:
    - 口感
    - 品牌形象
    - 包装设计
  复购概率: 0.75

商务人士:
  价格敏感度: 低
  品牌忠诚度: 中
  品质要求: 高
  决策速度: 快
  购买动机: 商务送礼、社交需求
  信息获取渠道:
    - 商业社交圈
    - 品牌直营店
    - 企业定制渠道
  购买影响因素:
    - 品牌知名度
    - 包装档次
    - 送礼价值
  复购概率: 0.65

健康生活主义者:
  价格敏感度: 中
  品牌忠诚度: 中
  品质要求: 高
  决策速度: 中
  购买动机: 健康养生、生活方式
  信息获取渠道:
    - 健康类APP
    - 社交媒体
    - 专业媒体
  购买影响因素:
    - 有机认证
    - 产品功效
    - 生态种植
  复购概率: 0.70

年轻新贵:
  价格敏感度: 中高
  品牌忠诚度: 低
  品质要求: 中高
  决策速度: 快
  购买动机: 尝鲜体验、社交分享
  信息获取渠道:
    - 小红书
    - 抖音
    - 社交媒体
  购买影响因素:
    - 新品体验
    - 社交价值
    - 包装设计
  复购概率: 0.55 