# 季节信息配置
seasons:
  春季: [1, 2, 3, 4, 5, 6, 7]  # 模拟的天数1-7为春季
  夏季: [8, 9, 10, 11, 12, 13, 14]  # 模拟的天数8-14为夏季
  秋季: [15, 16, 17, 18, 19, 20, 21]  # 模拟的天数15-21为秋季
  冬季: [22, 23, 24, 25, 26, 27, 28, 29, 30]  # 模拟的天数22-30为冬季

# 季节性产品偏好
seasonal_preferences:
  春季:
    - 银骏眉
    - 茶缘·春韵
    - 正山小种野茶
    - 初味红茶
    - 白毫银针
  夏季:
    - 铁观音
    - 白毫银针
    - 轻尝·红茶
    - 茶语·小红
    - 巴东红
  秋季:
    - 金骏眉特级
    - 正山小种特级
    - 妃子笑
    - 广元红
    - 察隅红
  冬季:
    - 金骏眉珍藏
    - 百年原生老枞
    - 宋风雅韵礼盒
    - 武夷秘传·1986
    - 经典马口罐礼盒

# 消费者群体季节性偏好
consumer_seasonal_preferences:
  传统茶文化爱好者:
    春季:
      - 银骏眉
      - 正山小种野茶
    夏季:
      - 铁观音
      - 白毫银针
    秋季:
      - 金骏眉特级
      - 正山小种特级
    冬季:
      - 金骏眉珍藏
      - 百年原生老枞
  品质生活追求者:
    春季:
      - 茶缘·春韵
      - 正山小种野茶
    夏季:
      - 轻尝·红茶
      - 白毫银针
    秋季:
      - 金骏眉特级
      - 妃子笑
    冬季:
      - 宋风雅韵礼盒
      - 金骏眉珍藏
  商务人士:
    春季:
      - 正山小种特级
      - 秘境寻踪礼盒
    夏季:
      - 大红袍
      - 经典马口罐礼盒
    秋季:
      - 全家福组合礼盒
      - 金骏眉珍藏
    冬季:
      - 茗品尊享礼盒
      - 武夷秘传·1986
  健康生活主义者:
    春季:
      - 初味红茶
      - 普安红
    夏季:
      - 巴东红
      - 白毫银针
    秋季:
      - 察隅红
      - 白沙红
    冬季:
      - 正山小种野茶
      - 古丈红
  年轻新贵:
    春季:
      - 茶缘·春韵
      - 茶语·小红
    夏季:
      - 轻尝·红茶
      - 铁观音
    秋季:
      - 妃子笑
      - 广元红
    冬季:
      - 秘境寻踪礼盒
      - 经典马口罐礼盒 